import MySQLdb
db=MySQLdb.connect("localhost","root","","cs564_abhishek")
c=db.cursor()
s1="""CREATE TABLE DEPARTMENT(DEPTID VARCHAR(10) PRIMARY KEY,NAME CHAR(25),FLOOR INT,BUILDINGno INT)"""
c.execute(s1)
s2="""CREATE TABLE USER(BANNERID INT PRIMARY KEY,NAME CHAR(30),ADDRESS VARCHAR(35),USERNAME VARCHAR(25),PASSWORD VARCHAR(20),ACCESSRIGHTS CHAR(5),DEPTID VARCHAR(10))"""
c.execute(s2)
s3="""CREATE TABLE LAB(LABID VARCHAR(10) PRIMARY KEY,NAME CHAR(20))"""
c.execute(s3)
s4="""CREATE TABLE ACTIVITY(AIV CHAR(5),LOGINTIME VARCHAR(20),LOGOUTTIME VARCHAR(20), LABID VARCHAR(10))"""
c.execute(s4)
s5="""CREATE TABLE LOCATION(BUILDINGno INT PRIMARY KEY,BUILDINGNAME CHAR(20),CAMPUSAREA CHAR(25))"""
c.execute(s5)
s6="""CREATE TABLE SYSTEM(MACaddress VARCHAR(20),IPaddress VARCHAR(20),SYSTEMNAME CHAR(20),OPERATINGSYSTEM CHAR(10))"""
c.execute(s6)
s7="""CREATE TABLE BELONGS_TO(DEPTID VARCHAR(10),LABID VARCHAR(10))"""
c.execute(s7)
s8="""CREATE TABLE ACCESS_TO(BANNERID INT,LABID VARCHAR(10))"""
c.execute(s8)
s9="""CREATE TABLE RECORDED_BY(BANNERID INT,AIV CHAR(5))"""
c.execute(s9)
s10="""CREATE TABLE AT(LABID VARCHAR(10),BUILDINGno INT)"""
c.execute(s10)
s11="""CREATE TABLE HAS(LABID VARCHAR(10),MACaddress VARCHAR(20))"""
c.execute(s11)

